version: '3.4'

services:
  web:
    build: ./shelter_v11
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./shelter_v11:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Passw0rd465
      POSTGRES_USER: pg-user
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
#      /var/lib/postgresql/data/pgdata
#      D:\Postgresql\data
    volumes:
      - ./postgresql:/var/lib/postgresql/data
#     - D:\Postgresql\data
